# Generated by Django 3.2.16 on 2022-12-16 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.IntegerField(max_length=7)),
                ('Stock', models.IntegerField(max_length=7)),
                ('Nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_productos',
            fields=[
                ('idLista', models.AutoField(primary_key=True, serialize=False)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.productos')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
